version: '3'

services:
  bai_api:
    container_name: bai-api 
    # environment:
      # DATABASE_URL: "postgres://postgres:${POSTGRES_PASSWORD}@db:5432"
    restart: unless-stopped
    build:
      context: ./bai
      dockerfile: Dockerfile
    ports:
      - "3000:3000"

  mythril:
    container_name: mythril 
    # environment:
      # DATABASE_URL: "postgres://postgres:${POSTGRES_PASSWORD}@db:5432"
    restart: unless-stopped
    build:
      context: ./mythril
      dockerfile: Dockerfile
    ports:
      - "4000:4000"

  caddy:
    image: caddy/caddy:2.7.5-alpine
    container_name: caddy-service
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:            
    - $PWD/Caddyfile:/etc/caddy/Caddyfile
    - $PWD/site:/srv
    - caddy_data:/data
    - caddy_config:/config

volumes:
  caddy_data:
  caddy_config: 