version: '3'

services:
  nascent-api:
    container_name: nascent-api 
    restart: unless-stopped
    build:
      context: ./bai
      dockerfile: Dockerfile
    ports:
      - "3000:3000"

  nascent-frontend:
    container_name: nascent-frontend 
    restart: unless-stopped
    build:
      context: ./mythril
      dockerfile: Dockerfile
    ports:
      - "8080:8080"

  caddy:
    image: caddy/caddy:2.7.5-alpine
    container_name: caddy-nascent
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:            
    - $PWD/Caddyfile:/etc/caddy/Caddyfile
    - $PWD/site:/srv
    - caddy_data:/data
    - caddy_config:/config

volumes:
  caddy_data:
  caddy_config: 